### ISSUE TITLE
Speedtest module

### ISSUE THREAD

**Issue by Innectic** [Innectic/starlink-outages#1]
Run a speed test once an hour, and store the results until reset is run. After each speed test, tweet the results. At reset time, tweet max, min, average test. Should also include the latency

**Comment by mihirterna** [comment]
Hi @Innectic , would like to work on it. Can you please assign it to me?

**Comment by Innectic** [comment]
@mihirterna Sorry about that, I didn't actually see this comment until just now, after I had got bored and just done it 😅 However, it is missing latency, if you would like to add that. Assigned!

**Comment by mihirterna** [comment]
Ok, cool, adding latency into hourly tweet .

**Comment by mihirterna** [comment]
Hi, Please review PR #4
